import { useEffect, useRef, useState } from 'react';
import { api } from '../api';
import { presentErrorText } from '../error-presentation';
import type { Anchor, DiscussionNode, Message, ProviderCatalog, Segment, WorkspaceSnapshot } from '../types';
export type SegmentRange = { messageId: string; selectedText: string; startOffset: number; endOffset: number };
export function ConversationManager({ node,segments,anchors,messages,catalog,range,onChanged,onLocate,onMerge }: { node: DiscussionNode; segments: Segment[]; anchors: Anchor[]; messages: Message[]; catalog: ProviderCatalog; range?: SegmentRange; onChanged: (workspace: WorkspaceSnapshot) => void; onLocate: (id: string) => void; onMerge: () => void }) {
  const [expanded,setExpanded]=useState(!!range);
  useEffect(()=>{if(range)setExpanded(true);},[range]);
  const [title,setTitle]=useState(node.title); const [segmentTitle,setSegmentTitle]=useState(''); const [selected,setSelected]=useState<string[]>([]); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const live=useRef(true); const scope=api.workspaceId();
  useEffect(()=>{live.current=true;return()=>{live.current=false;};},[]);
  useEffect(()=>{setTitle(node.title);},[node.title]);
  const act=async(work:()=>Promise<{workspace:WorkspaceSnapshot}>)=>{if(busy)return;setBusy(true);setError('');try{const result=await work();if(live.current&&scope===api.workspaceId())onChanged(result.workspace);}catch(error){if(live.current)setError(presentErrorText(error,{message:'操作失败。',recovery:'请检查输入后重试。'}));}finally{if(live.current)setBusy(false);}};
  return <details className="conversation-manager" open={expanded} onToggle={event=>setExpanded(event.currentTarget.open)}><summary>讨论与 Segment 管理</summary>
    {error&&<p role="alert">{error}</p>}
    {node.kind==='branch'&&node.status!=='archived'&&node.status!=='resolved'&&<button disabled={busy} onClick={onMerge}>选择合并目标</button>}
    <form onSubmit={event=>{event.preventDefault();void act(()=>api.renameConversation(node.id,title));}}><label>讨论名称<input value={title} maxLength={200} onChange={event=>setTitle(event.target.value)}/></label><button disabled={busy||node.status==='archived'}>保存名称</button></form>
    <label>讨论状态<select aria-label="讨论状态" value={node.status} disabled={busy} onChange={event=>void act(()=>api.setNodeStatus(node.id,event.target.value as DiscussionNode['status']))}>{['draft','active','resolved','stale','archived'].map(status=><option key={status} value={status}>{status}</option>)}</select></label>
    <label>本讨论模型<select aria-label="本讨论模型" value={node.preferredModelId??''} disabled={busy||node.status==='archived'} onChange={event=>void act(()=>api.setConversationModel(node.id,event.target.value||null))}><option value="">继承工作区默认模型</option>{catalog.models.map(model=><option key={model.id} value={model.id}>{model.displayName}</option>)}{node.preferredModelId&&!catalog.models.some(model=>model.id===node.preferredModelId)&&<option value={node.preferredModelId}>所选模型不可用</option>}</select></label>
    <form onSubmit={event=>{event.preventDefault();void act(()=>api.createSegment(node.id,segmentTitle,range?[range.messageId]:selected,range));setSegmentTitle('');}}><label>新 Segment 标题<input value={segmentTitle} maxLength={200} onChange={event=>setSegmentTitle(event.target.value)}/></label>{range?<blockquote>原始消息片段：{range.selectedText}</blockquote>:<label>消息范围<select multiple aria-label="Segment 消息范围" value={selected} onChange={event=>setSelected([...event.target.selectedOptions].map(option=>option.value))}>{messages.filter(message=>!message.pending).map(message=><option key={message.id} value={message.id}>{message.kind}: {message.text.slice(0,70)}</option>)}</select></label>}<button disabled={busy||!segmentTitle.trim()||node.status==='archived'}>创建 Segment</button></form>
    <ol>{segments.filter(segment=>segment.nodeId===node.id).map(segment=><li key={segment.id}><button onClick={()=>{const message=anchors.find(anchor=>anchor.segmentId===segment.id)?.messageId??messages.find(message=>message.segmentId===segment.id)?.id;if(message)onLocate(message);}}>{segment.title} {segment.status==='archived'?'（已归档）':''}</button><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void act(()=>api.updateSegment(segment.id,{title:String(form.get('title'))}));}}><input aria-label={`重命名 ${segment.title}`} name="title" defaultValue={segment.title} maxLength={200}/><button disabled={busy||node.status==='archived'}>重命名</button></form><button disabled={busy||node.status==='archived'} onClick={()=>void act(()=>api.updateSegment(segment.id,{status:segment.status==='archived'?'active':'archived'}))}>{segment.status==='archived'?'恢复 Segment':'归档 Segment'}</button></li>)}</ol>
  </details>;
}
